id: taxi_data_dbt_gcp_taxi_scheduled
namespace: taxi_gcp
description: |
  This flow downloads NYC taxi data (2019-2020) from GitHub,
  extracts and uploads it to Google Cloud Storage (GCS),
  and creates an external table in BigQuery.

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [yellow, green]
    defaults: green

variables:
  file: "{{inputs.taxi}}_tripdata_{{trigger.date | date('yyyy-MM')}}.csv"
  gcs_file: "gs://{{kv('GCP_BUCKET_NAME')}}/{{vars.file}}"
  table: "{{kv('GCP_DATASET')}}.{{inputs.taxi}}_tripdata_ext"
  data: "{{outputs.extract.outputFiles[inputs.taxi ~ '_tripdata_' ~ (trigger.date | date('yyyy-MM')) ~ '.csv']}}"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      taxi: "{{inputs.taxi}}"

  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO- https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{inputs.taxi}}/{{render(vars.file)}}.gz | gunzip > {{render(vars.file)}}

  - id: upload_to_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{render(vars.data)}}"
    to: "{{render(vars.gcs_file)}}"

  - id: create_external_table
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      -- Check if the external table exists
      DECLARE table_exists BOOL;
      SET table_exists = (
        SELECT COUNT(*)
        FROM `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.__TABLES__`
        WHERE table_id = '{{inputs.taxi}}_tripdata_ext'
      ) > 0;

      -- Create the external table if it does not exist
      IF table_exists = FALSE THEN
        CREATE EXTERNAL TABLE `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.{{inputs.taxi}}_tripdata_ext`
        OPTIONS (
          format = 'CSV',
          uris = ['gs://{{kv('GCP_BUCKET_NAME')}}/{{inputs.taxi}}_tripdata_*.csv'],
          skip_leading_rows = 1,
          ignore_unknown_values = TRUE
        );
      END IF;
  
  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: To avoid cluttering your storage, we will remove the downloaded files

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    inputs:
      taxi: green

  - id: yellow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 1 * *"
    inputs:
      taxi: yellow
